# Gitleaks Configuration for Security Scanning
# This file defines what patterns Gitleaks should look for when scanning for secrets

title = "Gitleaks Security Configuration"

# Global settings
[extend]
useDefault = true

# Allowlist configuration (correct format for Gitleaks v8.18.1)
[allowlist]
description = "Global allowlist rules"
regexes = [
    '''dummy.*''',
    '''example.*''',
    '''placeholder.*''',
    '''test.*''',
    '''fake.*''',
    '''AKIA.*EXAMPLE.*''',
    '''your-.*-here''',
    '''localhost''',
    '''127\.0\.0\.1''',
]

paths = [
    '''README\.md''',
    '''.*\.md''',
    '''docs/.*''',
    '''test/.*''',
    '''tests/.*''',
    '''.*/test/.*''',
    '''.*/tests/.*''',
    '''.*\.jpg''',
    '''.*\.jpeg''',
    '''.*\.png''',
    '''.*\.gif''',
    '''.*\.pdf''',
    '''.*\.zip''',
    '''.*\.tar\.gz''',
    '''node_modules/.*''',
    '''.git/.*''',
]